services:
  bolt:
    container_name: bolt-sqlite
    build:
      context: ../..
      dockerfile: docker/sqlite/Dockerfile
    volumes:
      - ../..:/app
      - vendor_data:/app/vendor
    networks:
      - bolt
    command: composer run test
volumes:
  vendor_data:
networks:
  bolt:
    driver: bridge
