services:
  bolt:
    build:
      context: ../..
      dockerfile: docker/sqlite/Dockerfile
    volumes:
      - ../..:/app
      - vendor_data:/app/vendor
    command: composer run test
volumes:
  vendor_data:
