services:
  bolt:
    build:
      context: ../..
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - ./../..:/app
      - vendor_data:/app/vendor
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=testing
      - DB_USERNAME=tester
      - DB_PASSWORD=password
    command: composer run test
  mysql:
    image: mysql:8.4
    container_name: bolt-mysql
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "tester", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  vendor_data:
